apiVersion: v1
kind: PersistentVolume
metadata:
   name: mongo-persistent-storage-persistentvolume

spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: //mypath
    type: DirectoryOrCreate