apiVersion: v1
kind: PersistentVolume
metadata:
   name: traefik-letsencrypt-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: //mypath
    type: DirectoryOrCreate